base_url = "https://gebhart.dev/"

compile_sass = true

build_search_index = false

title = "Nicholas Gebhart"
description = "Nicholas Gebhart is a Software Engineer"

generate_feed = true

[markdown]
highlight_code = false

[extra]
repo = "https://github.com/gebhartn/gebhart.dev"
profile = "profile.jpg"
